### ISSUE TITLE
`run` todo

### ISSUE THREAD

**Issue by bortok** [open-traffic-generator/otgen#2]
- [x] checkResponse for FlowMetric (if needed) - not needed
- [x] PortMetrics
- [x] read from stdin
- [x] json input
- [x] reporting interval as a parameter
- [x] ignore x.509 validation
- [x] default API endpoint to `https://localhost`

Next Release
- [x] log level option `--log`
- [x] read API URL from ENV:OTG_API, if no `--api` is given

Backlog
- [ ] metrics header, with on/off via a parameter
- [ ] grpc for API endpoint
- [ ] timeout for API communications
- [ ] pcap recording
- [ ] option to report multiple metrics types (port, flow)

**Comment by bortok** [comment]
reference for pcap implementation https://github.com/open-traffic-generator/conformance/blob/main/features/flows/headers/tcp/tcp_header_test.go#L53
