### ISSUE TITLE
`transform` todo

### ISSUE THREAD

**Issue by bortok** [open-traffic-generator/otgen#7]
- [ ] built-in pass-through template
- [ ] template `--file` parameter
- [ ] built-in template for PortMetric: frames
- [ ] built-in template for PortMetric: bytes, rate
- [ ] built-in template for FlowMetric
